using System;
using System.IO;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Formats.Png;
using SixLabors.ImageSharp.PixelFormats;

namespace PCL.Core.UI.Media;

public static class ImageConverter
{
    /// <summary>
    /// 从 WebP 输入流解码并转换为 PNG，返回包含 PNG 数据的 MemoryStream（Position=0）。
    /// 使用托管解码器，不依赖平台图像组件。
    /// </summary>
    /// <param name="input">输入 WebP 流（不会在此方法中关闭）</param>
    /// <param name="frameIndex">要提取的帧索引，默认 0</param>
    /// <returns>包含 PNG 数据的 MemoryStream，调用方负责释放</returns>
    /// <exception cref="ArgumentOutOfRangeException">帧索引超出图像支持范围</exception>
    /// <exception cref="NotSupportedException">系统缺少 WebP 解码器，或数据格式不受支持</exception>
    // Partly generated by gpt-5 (20250813)
    public static MemoryStream FromWebpToPng(this Stream input, int frameIndex = 0)
    {
        // 确保有可寻址的源流
        var source = input;
        MemoryStream? tempBuffer = null;
        if (!input.CanSeek)
        {
            tempBuffer = new MemoryStream();
            input.CopyTo(tempBuffer);
            tempBuffer.Position = 0;
            source = tempBuffer;
        }
        else
        {
            // 从开头解码
            if (source.Position != 0) source.Position = 0;
        }
        try
        {
            using var image = Image.Load(source);
            if (frameIndex < 0 || frameIndex >= image.Frames.Count)
                throw new ArgumentOutOfRangeException(nameof(frameIndex), $"帧索引超出范围（0..{image.Frames.Count - 1}）。");

            using var frame = image.Frames.CloneFrame(frameIndex);
            var output = new MemoryStream();
            frame.Save(output, new PngEncoder());
            output.Position = 0;
            return output;
        }
        catch (NotSupportedException)
        {
            // 透传，提示缺少编解码器或格式不支持
            throw;
        }
        catch (Exception ex)
        {
            // 统一转为更明确的异常信息（保留原始异常以便调试）
            throw new NotSupportedException("转换 WebP 到 PNG 失败：输入可能不是有效的 WebP，或系统未提供所需的编解码支持。", ex);
        }
        finally
        {
            // 仅释放我们创建的临时缓冲，不关闭调用方传入的 input
            tempBuffer?.Dispose();
        }
    }

    public static MemoryStream Bgra32ToPng(byte[] pixels, int width, int height)
    {
        ArgumentNullException.ThrowIfNull(pixels);
        if (width <= 0 || height <= 0 || pixels.Length != checked(width * height * 4))
            throw new ArgumentException("Pixel buffer dimensions do not match its length.", nameof(pixels));

        using var image = Image.LoadPixelData<Bgra32>(pixels, width, height);
        var output = new MemoryStream();
        image.Save(output, new PngEncoder());
        output.Position = 0;
        return output;
    }
}
